import React, { useEffect, useMemo, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faArrowRight, faEnvelope, faLock, faUser,
} from '@fortawesome/free-solid-svg-icons';
import { getConfig } from '@edx/frontend-platform';
import { sendPageEvent, sendTrackEvent } from '@edx/frontend-platform/analytics';
import { useIntl } from '@edx/frontend-platform/i18n';
import { Form, Spinner, StatefulButton } from '@openedx/paragon';
import classNames from 'classnames';
import PropTypes from 'prop-types';
import { Helmet } from 'react-helmet';
import Skeleton from 'react-loading-skeleton';
import ConfigurableRegistrationForm from './components/ConfigurableRegistrationForm';
import RegistrationFailure from './components/RegistrationFailure';
import {
  backupRegistrationFormBegin,
  clearRegistrationBackendError,
  registerNewUser,
  setEmailSuggestionInStore,
  setUserPipelineDataLoaded,
} from './data/actions';
import { FORM_SUBMISSION_ERROR, TPA_AUTHENTICATION_FAILURE } from './data/constants';
import getBackendValidations from './data/selectors';
import { isFormValid, prepareRegistrationPayload } from './data/utils';
import messages from './custommessages';
import  TermsOfService  from './RegistrationFields/TermsOfServiceField/CustomTermsOfService';
import CustomEmailField from './RegistrationFields/EmailField/CustomEmailField';
import CustomNameField from './RegistrationFields/NameField/CustomNameField.jsx';
import {
  InstitutionLogistration,
  RedirectLogistration,
  ThirdPartyAuthAlert,
  PasswordField,
} from '../common-components';
import CustomPasswordField from "../common-components/CustomPasswordField.jsx";
import { getThirdPartyAuthContext as getRegistrationDataFromBackend } from '../common-components/data/actions';
import EnterpriseSSO from '../common-components/EnterpriseSSO';
import ThirdPartyAuth from '../common-components/ThirdPartyAuth';
import { COMPLETE_STATE, PENDING_STATE, REGISTER_PAGE } from '../data/constants';
import {
  getAllPossibleQueryParams,
  getTpaHint,
  getTpaProvider,
  isHostAvailableInQueryParams,
  setCookie,
} from '../data/utils';
import './customregistration.scss';

const CustomRegistrationPage = ({ handleInstitutionLogin, institutionLogin }) => {
  const { formatMessage } = useIntl();
  const dispatch = useDispatch();
  const registrationEmbedded = isHostAvailableInQueryParams();
  const platformName = getConfig().SITE_NAME;

  const flags = {
    showConfigurableEdxFields: getConfig().SHOW_CONFIGURABLE_EDX_FIELDS,
    showConfigurableRegistrationFields: getConfig().ENABLE_DYNAMIC_REGISTRATION_FIELDS,
    showMarketingEmailOptInCheckbox: getConfig().MARKETING_EMAILS_OPT_IN,
    autoGeneratedUsernameEnabled: getConfig().ENABLE_AUTO_GENERATED_USERNAME,
  };

  const backedUpFormData = useSelector((state) => state.register.registrationFormData);
  const registrationError = useSelector((state) => state.register.registrationError);
  const registrationErrorCode = registrationError?.errorCode;
  const registrationResult = useSelector((state) => state.register.registrationResult);
  const shouldBackupState = useSelector((state) => state.register.shouldBackupState);
  const userPipelineDataLoaded = useSelector((state) => state.register.userPipelineDataLoaded);
  const submitState = useSelector((state) => state.register.submitState);
  const fieldDescriptions = useSelector((state) => state.commonComponents.fieldDescriptions);
  const optionalFields = useSelector((state) => state.commonComponents.optionalFields);
  const thirdPartyAuthApiStatus = useSelector((state) => state.commonComponents.thirdPartyAuthApiStatus);
  const autoSubmitRegForm = useSelector(
    (state) => state.commonComponents.thirdPartyAuthContext.autoSubmitRegForm
  );
  const thirdPartyAuthErrorMessage = useSelector(
    (state) => state.commonComponents.thirdPartyAuthContext.errorMessage
  );
  const finishAuthUrl = useSelector(
    (state) => state.commonComponents.thirdPartyAuthContext.finishAuthUrl
  );
  const currentProvider = useSelector(
    (state) => state.commonComponents.thirdPartyAuthContext.currentProvider
  );
  const providers = useSelector((state) => state.commonComponents.thirdPartyAuthContext.providers);
  const secondaryProviders = useSelector(
    (state) => state.commonComponents.thirdPartyAuthContext.secondaryProviders
  );
  const hasThirdPartyAuthOptions = !currentProvider && (providers.length > 0 || secondaryProviders.length > 0);
  const pipelineUserDetails = useSelector(
    (state) => state.commonComponents.thirdPartyAuthContext.pipelineUserDetails
  );
  const backendValidations = useSelector(getBackendValidations);

  const queryParams = useMemo(() => getAllPossibleQueryParams(), []);
  const tpaHint = useMemo(() => getTpaHint(), []);

  const [formFields, setFormFields] = useState({
    name: '',
    email: '',
    username: '',
    password: '',
    confirm_password: '',
    user_role: '',
    terms_of_service: false,
    ...backedUpFormData.formFields,
  });

  const [configurableFormFields, setConfigurableFormFields] = useState({
    ...backedUpFormData.configurableFormFields,
  });

  const [errors, setErrors] = useState({ ...backedUpFormData.errors });
  const [errorCode, setErrorCode] = useState({ type: '', count: 0 });
  const [formStartTime, setFormStartTime] = useState(null);
  const [temporaryErrors, setTemporaryErrors] = useState({ ...backedUpFormData.errors });
  const [registrationComplete, setRegistrationComplete] = useState(false);

  const { cta, host } = queryParams;
  const buttonLabel = cta
    ? formatMessage(messages['create.account.cta.button'], { label: cta })
    : formatMessage(messages['create.account.for.free.button']);

  useEffect(() => {
    if (!formStartTime) {
      sendPageEvent('login_and_registration', 'register');
      const payload = { ...queryParams, is_register_page: true };
      if (tpaHint) payload.tpa_hint = tpaHint;
      dispatch(getRegistrationDataFromBackend(payload));
      setFormStartTime(Date.now());
    }
  }, [dispatch, formStartTime, queryParams, tpaHint]);

  useEffect(() => {
    if (shouldBackupState) {
      dispatch(
        backupRegistrationFormBegin({
          ...backedUpFormData,
          configurableFormFields: { ...configurableFormFields },
          formFields: { ...formFields },
          errors: { ...errors },
        })
      );
    }
  }, [shouldBackupState, configurableFormFields, formFields, errors, dispatch, backedUpFormData]);

  useEffect(() => {
    if (backendValidations) {
      const target = registrationEmbedded ? setTemporaryErrors : setErrors;
      target((prev) => ({ ...prev, ...backendValidations }));
    }
  }, [backendValidations, registrationEmbedded]);

  useEffect(() => {
    if (registrationErrorCode) {
      setErrorCode((prevState) => ({ type: registrationErrorCode, count: prevState.count + 1 }));
    }
  }, [registrationErrorCode]);

  useEffect(() => {
    if (registrationResult.success) {
      sendTrackEvent('edx.bi.user.account.registered.client', {});
      setCookie(getConfig().USER_RETENTION_COOKIE_NAME, true);
      setRegistrationComplete(true);
    }
  }, [registrationResult]);

  useEffect(() => {
    if (!userPipelineDataLoaded && thirdPartyAuthApiStatus === COMPLETE_STATE) {
      if (thirdPartyAuthErrorMessage) {
        setErrorCode(prevState => ({ type: TPA_AUTHENTICATION_FAILURE, count: prevState.count + 1 }));
      }
      if (pipelineUserDetails && Object.keys(pipelineUserDetails).length !== 0) {
        const { name = '', username = '', email = '' } = pipelineUserDetails;
        setFormFields(prevState => ({
          ...prevState,
          name,
          username,
          email,
        }));
        dispatch(setUserPipelineDataLoaded(true));
      }
    }
  }, [
    thirdPartyAuthApiStatus,
    thirdPartyAuthErrorMessage,
    pipelineUserDetails,
    userPipelineDataLoaded,
    dispatch,
  ]);

  const handleOnChange = (event) => {
    const { name } = event.target;
    const value = event.target.type === 'checkbox' ? event.target.checked : event.target.value;

    if (registrationError[name]) {
      dispatch(clearRegistrationBackendError(name));
    }

    setErrors((prev) => ({ ...prev, [name]: '' }));
    setFormFields((prev) => ({ ...prev, [name]: value }));

    if (name === 'password' || name === 'confirm_password') {
      const newPw = name === 'password' ? value : formFields.password;
      const newConfirm = name === 'confirm_password' ? value : formFields.confirm_password;
      if (newConfirm && newPw !== newConfirm) {
        setErrors((prev) => ({
          ...prev,
          confirm_password: formatMessage(messages['registration.passwords.do.not.match']),
        }));
      } else {
        setErrors((prev) => ({ ...prev, confirm_password: '' }));
      }
    }

    if (!value && ['name', 'email', 'password', 'confirm_password'].includes(name)) {
      setErrors((prev) => ({
        ...prev,
        [name]: formatMessage(messages[`empty.${name}.field.error`] || messages['registration.field.required.generic']),
      }));
    }

    if (name === 'user_role' && !value) {
      setErrors((prev) => ({
        ...prev,
        user_role: formatMessage(messages['registration.user.role.required.error']),
      }));
    }

    if (name === 'terms_of_service' && !value) {
      setErrors((prev) => ({
        ...prev,
        terms_of_service: formatMessage(messages['registration.terms.required.error']),
      }));
    }
  };

  const handleErrorChange = (fieldName, error) => {
    if (registrationEmbedded) {
      setTemporaryErrors((prev) => ({ ...prev, [fieldName]: error }));
      if (error === '' && errors[fieldName]) {
        setErrors((prev) => ({ ...prev, [fieldName]: '' }));
      }
    } else {
      setErrors((prev) => ({ ...prev, [fieldName]: error }));
    }
  };

  const registerUser = () => {
    const totalRegistrationTime = (Date.now() - formStartTime) / 1000;

    let payload = {
      name: (formFields.name || '').trim(),
      email: (formFields.email || '').trim(),
      username: (formFields.username || formFields.email || '').trim(),
      user_role: formFields.user_role || '',
      terms_of_service: formFields.terms_of_service,
    };

    if (currentProvider) {
      payload.social_auth_provider = currentProvider;
    } else {
      payload.password = formFields.password || '';
    }

    const customErrors = {};

    if (!payload.name) customErrors.name = formatMessage(messages['empty.name.field.error']);
    if (!payload.email) customErrors.email = formatMessage(messages['empty.email.field.error']);
    if (!payload.user_role) customErrors.user_role = formatMessage(messages['registration.user.role.required.error']);
    if (!payload.terms_of_service) customErrors.terms_of_service = formatMessage(messages['registration.terms.required.error']);

    if (!currentProvider) {
      if (!formFields.password?.trim()) {
        customErrors.password = formatMessage(messages['empty.password.field.error']);
      }
      if (!formFields.confirm_password?.trim()) {
        customErrors.confirm_password = formatMessage(messages['empty.confirm_password.field.error']);
      }
      if (formFields.password !== formFields.confirm_password) {
        customErrors.confirm_password = formatMessage(messages['registration.passwords.do.not.match']);
      }
    }

    const {
      isValid: standardIsValid,
      fieldErrors: standardErrors,
      emailSuggestion,
    } = isFormValid(
      payload,
      registrationEmbedded ? temporaryErrors : errors,
      configurableFormFields,
      fieldDescriptions,
      formatMessage
    );

    const allFieldErrors = { ...standardErrors, ...customErrors };
    setErrors((prev) => ({ ...prev, ...allFieldErrors }));
    dispatch(setEmailSuggestionInStore(emailSuggestion));

    if (!standardIsValid || Object.keys(customErrors).length > 0) {
      setErrorCode((prev) => ({ type: FORM_SUBMISSION_ERROR, count: prev.count + 1 }));
      return;
    }

    const finalPayload = prepareRegistrationPayload(
      payload,
      configurableFormFields,
      flags.showMarketingEmailOptInCheckbox,
      totalRegistrationTime,
      queryParams
    );

    delete finalPayload.confirm_password;

    dispatch(registerNewUser(finalPayload));
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    registerUser();
  };

  const renderForm = () => {
    if (institutionLogin) {
      return (
        <InstitutionLogistration
          secondaryProviders={secondaryProviders}
          headingTitle={formatMessage(messages['register.institution.login.page.title'])}
        />
      );
    }

    return (
      <>
        <Helmet>
          <title>{formatMessage(messages['register.page.title'], { siteName: platformName })}</title>
        </Helmet>

        {registrationComplete ? (
          registrationResult.authenticatedUser?.isThirdPartyUser ? (
            <RedirectLogistration
              host={host}
              authenticatedUser={registrationResult.authenticatedUser}
              success={registrationResult.success}
              redirectUrl={registrationResult.redirectUrl}
              finishAuthUrl={finishAuthUrl}
              optionalFields={optionalFields}
              registrationEmbedded={registrationEmbedded}
              redirectToProgressiveProfilingPage={
                getConfig().ENABLE_PROGRESSIVE_PROFILING_ON_AUTHN &&
                !!Object.keys(optionalFields.fields).length
              }
            />
          ) : (
            <div className="mw-xs mt-5 text-center p-4 bg-light border rounded">
              <h4 className="text-success mb-3">{formatMessage(messages['registration.success.title'])}</h4>
              <div className="alert alert-success mb-4">
                {formatMessage(messages['registration.success.check.email.before'])}
                <strong className="ml-1 mr-1">{formFields.email}</strong>
                {formatMessage(messages['registration.success.check.email.after'])}
              </div>
            </div>
          )
        ) : submitState === 'pending' || (autoSubmitRegForm && !errorCode.type) ? (
          <div className="mw-xs mt-5 text-center">
            <Spinner animation="border" variant="primary" />
            <p className="mt-3">{formatMessage(messages['creating.account.message'])}</p>
          </div>
        ) : (
          <div
            className={classNames('mw-xs mt-3', {
              'w-100 m-auto pt-4 main-content': registrationEmbedded,
            })}
          >
            <ThirdPartyAuthAlert
              currentProvider={currentProvider}
              platformName={platformName}
              referrer={REGISTER_PAGE}
            />

            <RegistrationFailure
              errorCode={errorCode.type}
              failureCount={errorCode.count}
              context={{ provider: currentProvider, errorMessage: thirdPartyAuthErrorMessage }}
            />

            {!registrationEmbedded && hasThirdPartyAuthOptions && (
              <div className="custom-auth-tpa">
                <ThirdPartyAuth
                  currentProvider={currentProvider}
                  providers={providers}
                  secondaryProviders={secondaryProviders}
                  handleInstitutionLogin={handleInstitutionLogin}
                  thirdPartyAuthApiStatus={thirdPartyAuthApiStatus}
                />
                <div className="reg-auth-divider"><span>Or</span></div>
              </div>
            )}

            <Form id="registration-form" name="registration-form" noValidate onSubmit={handleSubmit}>
              <div className="row">
                <div className="col-md-6">
                  <div className="reg-input-group">
                    <span className="reg-input-icon" aria-hidden="true">
                      <FontAwesomeIcon icon={faUser} />
                    </span>
                    <CustomNameField
                      name="name"
                      value={formFields.name}
                      handleChange={handleOnChange}
                      handleErrorChange={handleErrorChange}
                      errorMessage={errors.name}
                      helpText={[formatMessage(messages['help.text.name'])]}
                      label={formatMessage(messages['registration.fullname.label'])}
                      placeholder={formatMessage(messages['registration.fullname.placeholder'])}
                    />
                  </div>
                </div>
                <div className="col-md-6">
                  <div className="reg-input-group reg-input-group-email">
                    <span className="reg-input-icon" aria-hidden="true">
                      <FontAwesomeIcon icon={faEnvelope} />
                    </span>
                    <CustomEmailField
                      disabled={!!currentProvider}
                      readOnly={!!currentProvider}
                      name="email"
                      value={formFields.email}
                      handleChange={handleOnChange}
                      handleErrorChange={handleErrorChange}
                      errorMessage={errors.email || errors.username}
                      helpText={[formatMessage(messages['help.text.email'])]}
                      label={formatMessage(messages['registration.email.label'])}
                      placeholder={formatMessage(messages['registration.email.placeholder'])}
                    />
                  </div>
                </div>
              </div>

              {!currentProvider && (
                <div className="row">
                  <div className="col-md-6">
                    <div className="reg-input-group">
                      <span className="reg-input-icon" aria-hidden="true">
                        <FontAwesomeIcon icon={faLock} />
                      </span>
                      <CustomPasswordField
                        name="password"
                        value={formFields.password}
                        handleChange={handleOnChange}
                        handleErrorChange={handleErrorChange}
                        errorMessage={errors.password}
                        label={formatMessage(messages['registration.password.label'])}
                        placeholder={formatMessage(messages['registration.password.placeholder'])}
                      />
                    </div>
                  </div>
                  <div className="col-md-6">
                    <div className="reg-input-group">
                      <span className="reg-input-icon" aria-hidden="true">
                        <FontAwesomeIcon icon={faLock} />
                      </span>
                      <CustomPasswordField
                        name="confirm_password"
                        value={formFields.confirm_password || ''}
                        handleChange={handleOnChange}
                        handleErrorChange={handleErrorChange}
                        errorMessage={errors.confirm_password}
                        label={formatMessage(messages['registration.confirm.password.label'])}
                        placeholder={formatMessage(messages['registration.confirm.password.placeholder'])}
                      />
                    </div>
                  </div>
                </div>
              )}

              <Form.Group className="mb-4 user-role-option">
                <Form.Label className="fw-medium mb-2">
                  {formatMessage(messages['registration.user.role.label'])}
                </Form.Label>

                <div className="row g-3">
                  {[
                    { value: 'student', label: formatMessage(messages['registration.user.role.option.student']) },
                    { value: 'mentor', label: formatMessage(messages['registration.user.role.option.mentor']) },
                  ].map((role) => (
                    <div className="col-12 col-sm-6" key={role.value}>
                      <label
                        className={classNames(
                          'd-flex align-items-center justify-content-center p-2 rounded border text-center w-100',
                          {
                            'border-primary bg-primary bg-opacity-10 text-white': formFields.user_role === role.value,
                            'border-secondary': formFields.user_role !== role.value,
                          }
                        )}
                      >
                        <input
                          type="radio"
                          name="user_role"
                          value={role.value}
                          checked={formFields.user_role === role.value}
                          onChange={handleOnChange}
                          className="sr-only"
                          required
                        />
                        {role.label}
                      </label>
                    </div>
                  ))}
                </div>

                {errors.user_role && (
                  <Form.Text className="text-danger mt-2">{errors.user_role}</Form.Text>
                )}
              </Form.Group>

              <TermsOfService
                value={formFields.terms_of_service}
                onChangeHandler={handleOnChange}
                errorMessage={errors.terms_of_service || ''}
              />

              <StatefulButton
                id="register-user"
                name="register-user"
                type="submit"
                variant="primary"
                className="register-button mt-4 mb-4 w-100 text-white"
                state={submitState}
                labels={{
                  default: (
                    <>
                      {buttonLabel}
                      <FontAwesomeIcon icon={faArrowRight} className="ml-2" />
                    </>
                  ),
                  pending: '',
                }}
              />
            </Form>
          </div>
        )}
      </>
    );
  };

  if (tpaHint) {
    if (thirdPartyAuthApiStatus === PENDING_STATE) return <Skeleton height={36} />;
    const { provider, skipHintedLogin } = getTpaProvider(tpaHint, providers, secondaryProviders);
    if (skipHintedLogin) {
      window.location.href = getConfig().LMS_BASE_URL + provider.registerUrl;
      return null;
    }
    return provider ? <EnterpriseSSO provider={provider} /> : renderForm();
  }

  return renderForm();
};

CustomRegistrationPage.propTypes = {
  institutionLogin: PropTypes.bool,
  handleInstitutionLogin: PropTypes.func,
};

CustomRegistrationPage.defaultProps = {
  handleInstitutionLogin: null,
  institutionLogin: false,
};

export default CustomRegistrationPage;