import React, { useEffect, useMemo, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { getConfig } from '@edx/frontend-platform';
import { sendPageEvent, sendTrackEvent } from '@edx/frontend-platform/analytics';
import { useIntl } from '@edx/frontend-platform/i18n';
import { Form, Spinner, StatefulButton } from '@openedx/paragon';
import classNames from 'classnames';
import PropTypes from 'prop-types';
import { Helmet } from 'react-helmet';
import Skeleton from 'react-loading-skeleton';

import ConfigurableRegistrationForm from './components/ConfigurableRegistrationForm';
import RegistrationFailure from './components/RegistrationFailure';
import {
  backupRegistrationFormBegin,
  clearRegistrationBackendError,
  registerNewUser,
  setEmailSuggestionInStore,
  setUserPipelineDataLoaded,
} from './data/actions';
import { FORM_SUBMISSION_ERROR, TPA_AUTHENTICATION_FAILURE } from './data/constants';
import getBackendValidations from './data/selectors';
import { isFormValid, prepareRegistrationPayload } from './data/utils';
import messages from './messages';
import { EmailField, NameField, TermsOfService } from './RegistrationFields';
import {
  InstitutionLogistration,
  RedirectLogistration,
  ThirdPartyAuthAlert,
  PasswordField,
} from '../common-components';
import { getThirdPartyAuthContext as getRegistrationDataFromBackend } from '../common-components/data/actions';
import EnterpriseSSO from '../common-components/EnterpriseSSO';
import ThirdPartyAuth from '../common-components/ThirdPartyAuth';
import { COMPLETE_STATE, PENDING_STATE, REGISTER_PAGE } from '../data/constants';
import {
  getAllPossibleQueryParams,
  getTpaHint,
  getTpaProvider,
  isHostAvailableInQueryParams,
  setCookie,
} from '../data/utils';

const CustomRegistrationPage = ({ handleInstitutionLogin, institutionLogin }) => {
  const { formatMessage } = useIntl();
  const dispatch = useDispatch();

  const registrationEmbedded = isHostAvailableInQueryParams();
  const platformName = getConfig().SITE_NAME;

  const flags = {
    showConfigurableEdxFields: getConfig().SHOW_CONFIGURABLE_EDX_FIELDS,
    showConfigurableRegistrationFields: getConfig().ENABLE_DYNAMIC_REGISTRATION_FIELDS,
    showMarketingEmailOptInCheckbox: getConfig().MARKETING_EMAILS_OPT_IN,
    autoGeneratedUsernameEnabled: getConfig().ENABLE_AUTO_GENERATED_USERNAME,
  };

  const backedUpFormData = useSelector((state) => state.register.registrationFormData);
  const registrationError = useSelector((state) => state.register.registrationError);
  const registrationErrorCode = registrationError?.errorCode;
  const registrationResult = useSelector((state) => state.register.registrationResult);
  const shouldBackupState = useSelector((state) => state.register.shouldBackupState);
  const userPipelineDataLoaded = useSelector((state) => state.register.userPipelineDataLoaded);
  const submitState = useSelector((state) => state.register.submitState);
  const fieldDescriptions = useSelector((state) => state.commonComponents.fieldDescriptions);
  const optionalFields = useSelector((state) => state.commonComponents.optionalFields);
  const thirdPartyAuthApiStatus = useSelector((state) => state.commonComponents.thirdPartyAuthApiStatus);
  const autoSubmitRegForm = useSelector(
    (state) => state.commonComponents.thirdPartyAuthContext.autoSubmitRegForm
  );
  const thirdPartyAuthErrorMessage = useSelector(
    (state) => state.commonComponents.thirdPartyAuthContext.errorMessage
  );
  const finishAuthUrl = useSelector(
    (state) => state.commonComponents.thirdPartyAuthContext.finishAuthUrl
  );
  const currentProvider = useSelector(
    (state) => state.commonComponents.thirdPartyAuthContext.currentProvider
  );
  const providers = useSelector((state) => state.commonComponents.thirdPartyAuthContext.providers);
  const secondaryProviders = useSelector(
    (state) => state.commonComponents.thirdPartyAuthContext.secondaryProviders
  );
  const pipelineUserDetails = useSelector(
    (state) => state.commonComponents.thirdPartyAuthContext.pipelineUserDetails
  );
  const backendValidations = useSelector(getBackendValidations);

  const queryParams = useMemo(() => getAllPossibleQueryParams(), []);
  const tpaHint = useMemo(() => getTpaHint(), []);

  const [formFields, setFormFields] = useState({
    name: '',
    email: '',
    // username: '',
    password: '',
    confirm_password: '',
    user_role: 'student',
    phone_number: '',
    terms_of_service: false,
    ...backedUpFormData.formFields,
  });

  const [configurableFormFields, setConfigurableFormFields] = useState({
    ...backedUpFormData.configurableFormFields,
  });

  const [errors, setErrors] = useState({ ...backedUpFormData.errors });
  const [errorCode, setErrorCode] = useState({ type: '', count: 0 });
  const [formStartTime, setFormStartTime] = useState(null);
  const [temporaryErrors, setTemporaryErrors] = useState({ ...backedUpFormData.errors });
  const [registrationComplete, setRegistrationComplete] = useState(false);

  const [otpState, setOtpState] = useState({
    sending: false,
    verifying: false,
    resending: false,
    otpSent: false,
    otpVerified: false,
    otpCode: '',
    verificationKey: '',
    resendIn: 0,
    expiresIn: 0,
    serverMessage: '',
  });

  const { cta, host } = queryParams;
  const buttonLabel = cta
    ? formatMessage(messages['create.account.cta.button'], { label: cta })
    : formatMessage(messages['create.account.for.free.button']);

  const otpApiBase = `${getConfig().LMS_BASE_URL}`;

  // useEffect(() => {
  //   if (formFields.email?.trim()) {
  //     setFormFields((prev) => ({
  //       ...prev,
  //       username: prev.email.trim(),
  //     }));
  //   }
  // }, [formFields.email]);

  useEffect(() => {
    if (otpState.resendIn <= 0) return;
    const timer = setInterval(() => {
      setOtpState((prev) => ({
        ...prev,
        resendIn: prev.resendIn > 0 ? prev.resendIn - 1 : 0,
      }));
    }, 1000);
    return () => clearInterval(timer);
  }, [otpState.resendIn]);

  const sendOtp = async () => {
    const phone = formFields.phone_number?.trim();
    if (!phone) {
      setErrors((prev) => ({ ...prev, phone_number: formatMessage(messages['registration.phone.number.required.error']) }));
      return;
    }
    setOtpState((prev) => ({ ...prev, sending: true, serverMessage: '' }));
    try {
      const res = await fetch(`${otpApiBase}/otp/send/`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ contact_identifier: phone }),
      });
      const data = await res.json();
      if (!res.ok || !data.success) {
        setOtpState((prev) => ({
          ...prev,
          sending: false,
          serverMessage: data.message || 'Failed to send OTP',
        }));
        return;
      }
      setOtpState((prev) => ({
        ...prev,
        sending: false,
        otpSent: true,
        otpVerified: false,
        verificationKey: data.verification_key,
        resendIn: data.resend_after_seconds || 30,
        expiresIn: data.expires_in_seconds || 300,
        serverMessage: 'OTP sent',
      }));
    } catch {
      setOtpState((prev) => ({ ...prev, sending: false, serverMessage: 'Network error' }));
    }
  };

  const resendOtp = async () => {
    const phone = formFields.phone_number?.trim();
    setOtpState((prev) => ({ ...prev, resending: true, serverMessage: '' }));
    try {
      const res = await fetch(`${otpApiBase}/otp/resend/`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ contact_identifier: phone }),
      });
      const data = await res.json();
      if (!res.ok || !data.success) {
        setOtpState((prev) => ({
          ...prev,
          resending: false,
          serverMessage: data.message || 'Failed to resend OTP',
        }));
        return;
      }
      setOtpState((prev) => ({
        ...prev,
        resending: false,
        otpSent: true,
        otpVerified: false,
        verificationKey: data.verification_key,
        resendIn: data.resend_after_seconds || 30,
        serverMessage: 'OTP resent',
      }));
    } catch {
      setOtpState((prev) => ({ ...prev, resending: false, serverMessage: 'Network error' }));
    }
  };

  const verifyOtp = async () => {
    const phone = formFields.phone_number?.trim();
    const code = otpState.otpCode?.trim();
    if (!code) {
      setOtpState((prev) => ({ ...prev, serverMessage: formatMessage(messages['registration.otp.required.error']) }));
      return;
    }
    setOtpState((prev) => ({ ...prev, verifying: true, serverMessage: '' }));
    try {
      const res = await fetch(`${otpApiBase}/otp/verify/`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contact_identifier: phone,
          otp_code: code,
          verification_key: otpState.verificationKey,
        }),
      });
      const data = await res.json();
      if (!res.ok || !data.success) {
        setOtpState((prev) => ({
          ...prev,
          verifying: false,
          serverMessage: data.message || 'Invalid OTP',
        }));
        return;
      }
      setOtpState((prev) => ({
        ...prev,
        verifying: false,
        otpVerified: true,
        serverMessage: 'Phone verified!',
      }));
    } catch {
      setOtpState((prev) => ({ ...prev, verifying: false, serverMessage: 'Network error' }));
    }
  };

  useEffect(() => {
    if (!formStartTime) {
      sendPageEvent('login_and_registration', 'register');
      const payload = { ...queryParams, is_register_page: true };
      if (tpaHint) payload.tpa_hint = tpaHint;
      dispatch(getRegistrationDataFromBackend(payload));
      setFormStartTime(Date.now());
    }
  }, [dispatch, formStartTime, queryParams, tpaHint]);

  useEffect(() => {
    if (shouldBackupState) {
      dispatch(
        backupRegistrationFormBegin({
          ...backedUpFormData,
          configurableFormFields: { ...configurableFormFields },
          formFields: { ...formFields },
          errors: { ...errors },
        })
      );
    }
  }, [shouldBackupState, configurableFormFields, formFields, errors, dispatch, backedUpFormData]);

  useEffect(() => {
    if (backendValidations) {
      const target = registrationEmbedded ? setTemporaryErrors : setErrors;
      target((prev) => ({ ...prev, ...backendValidations }));
    }
  }, [backendValidations, registrationEmbedded]);

  useEffect(() => {
    if (registrationErrorCode) {
      setErrorCode((prevState) => ({ type: registrationErrorCode, count: prevState.count + 1 }));
    }
  }, [registrationErrorCode]);

  useEffect(() => {
    if (registrationResult.success) {
      sendTrackEvent('edx.bi.user.account.registered.client', {});
      setCookie(getConfig().USER_RETENTION_COOKIE_NAME, true);
      setRegistrationComplete(true);
    }
  }, [registrationResult]);


  const handleOnChange = (event) => {
    const { name } = event.target;
    const value = event.target.type === 'checkbox' ? event.target.checked : event.target.value;

    if (registrationError[name]) {
      dispatch(clearRegistrationBackendError(name));
    }

    setErrors((prev) => ({ ...prev, [name]: '' }));
    setFormFields((prev) => ({ ...prev, [name]: value }));

    if (name === 'password' || name === 'confirm_password') {
      const newPw = name === 'password' ? value : formFields.password;
      const newConfirm = name === 'confirm_password' ? value : formFields.confirm_password;
      if (newConfirm && newPw !== newConfirm) {
        setErrors((prev) => ({ ...prev, confirm_password: formatMessage(messages['registration.passwords.do.not.match']) }));
      } else {
        setErrors((prev) => ({ ...prev, confirm_password: '' }));
      }
    }

    if (name === 'phone_number') {
      setOtpState({
        sending: false,
        verifying: false,
        resending: false,
        otpSent: false,
        otpVerified: false,
        otpCode: '',
        verificationKey: '',
        resendIn: 0,
        expiresIn: 0,
        serverMessage: '',
      });
    }
  };

  const handleErrorChange = (fieldName, error) => {
    if (registrationEmbedded) {
      setTemporaryErrors((prev) => ({ ...prev, [fieldName]: error }));
      if (error === '' && errors[fieldName]) {
        setErrors((prev) => ({ ...prev, [fieldName]: '' }));
      }
    } else {
      setErrors((prev) => ({ ...prev, [fieldName]: error }));
    }
  };

  const registerUser = () => {
    const totalRegistrationTime = (Date.now() - formStartTime) / 1000;

    if (!otpState.otpVerified) {
      setOtpState((prev) => ({
        ...prev,
        serverMessage: formatMessage(messages['registration.verify.phone.first']),
      }));
      return;
    }

    if (formFields.password !== formFields.confirm_password) {
      setErrors((prev) => ({
        ...prev,
        confirm_password: formatMessage(messages['registration.passwords.do.not.match']),
      }));
      return;
    }

    if (!formFields.terms_of_service) {
      setErrors((prev) => ({
        ...prev,
        terms_of_service: formatMessage(messages['terms.of.service']),
      }));
      return;
    }

    let payload = {
      name: (formFields.name || '').trim(),
      email: (formFields.email || '').trim(),
      username: (formFields.email || '').trim(),
      password: formFields.password || '',
      user_role: formFields.user_role || 'student',
      phone_number: (formFields.phone_number || '').trim(),
      terms_of_service: formFields.terms_of_service,
    };

    if (currentProvider) {
      delete payload.password;
      payload.social_auth_provider = currentProvider;
    }

    const { isValid, fieldErrors, emailSuggestion } = isFormValid(
      payload,
      registrationEmbedded ? temporaryErrors : errors,
      configurableFormFields,
      fieldDescriptions,
      formatMessage
    );

    setErrors(fieldErrors);
    dispatch(setEmailSuggestionInStore(emailSuggestion));

    if (!isValid) {
      setErrorCode((prev) => ({ type: FORM_SUBMISSION_ERROR, count: prev.count + 1 }));
      return;
    }

    const finalPayload = prepareRegistrationPayload(
      payload,
      configurableFormFields,
      flags.showMarketingEmailOptInCheckbox,
      totalRegistrationTime,
      queryParams
    );

    delete finalPayload.confirm_password;
    finalPayload.verification_key = otpState.verificationKey || undefined;

    dispatch(registerNewUser(finalPayload));
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    registerUser();
  };

  // useEffect(() => {
  //   if (autoSubmitRegForm && userPipelineDataLoaded) {
  //     registerUser();
  //   }
  // }, [autoSubmitRegForm, userPipelineDataLoaded]);

  const renderForm = () => {
    if (institutionLogin) {
      return (
        <InstitutionLogistration
          secondaryProviders={secondaryProviders}
          headingTitle={formatMessage(messages['register.institution.login.page.title'])}
        />
      );
    }

    return (
      <>
        <Helmet>
          <title>{formatMessage(messages['register.page.title'], { siteName: platformName })}</title>
        </Helmet>

        {/* {!registrationResult.success && (
          <RedirectLogistration
            host={host}
            authenticatedUser={registrationResult.authenticatedUser}
            success={registrationResult.success}
            redirectUrl={registrationResult.redirectUrl}
            finishAuthUrl={finishAuthUrl}
            optionalFields={optionalFields}
            registrationEmbedded={registrationEmbedded}
            redirectToProgressiveProfilingPage={
              getConfig().ENABLE_PROGRESSIVE_PROFILING_ON_AUTHN &&
              !!Object.keys(optionalFields.fields).length
            }
          />
        )} */}

        {registrationComplete ? (
          <div className="mw-xs mt-5 text-center p-4 bg-light border rounded">
            <h4 className="text-success mb-3">{formatMessage(messages['registration.success.title'])}</h4>
            <div className="alert alert-success mb-4">
              {formatMessage(messages['registration.success.check.email'], { email: formFields.email })}
            </div>
          </div>
        ) : submitState === 'pending' || (autoSubmitRegForm && !errorCode.type) ? (
          <div className="mw-xs mt-5 text-center">
            <Spinner animation="border" variant="primary" />
            <p className="mt-3">{formatMessage(messages['creating.account.message'])}</p>
          </div>
        ) : (
          <div
            className={classNames('mw-xs mt-3', {
              'w-100 m-auto pt-4 main-content': registrationEmbedded,
            })}
          >
            <ThirdPartyAuthAlert
              currentProvider={currentProvider}
              platformName={platformName}
              referrer={REGISTER_PAGE}
            />
            <RegistrationFailure
              errorCode={errorCode.type}
              failureCount={errorCode.count}
              context={{ provider: currentProvider, errorMessage: thirdPartyAuthErrorMessage }}
            />

            <Form id="registration-form" name="registration-form" noValidate onSubmit={handleSubmit}>
              <NameField
                name="name"
                value={formFields.name}
                handleChange={handleOnChange}
                handleErrorChange={handleErrorChange}
                errorMessage={errors.name}
                helpText={[formatMessage(messages['help.text.name'])]}
                floatingLabel={formatMessage(messages['registration.fullname.label'])}
              />

              <EmailField
                name="email"
                value={formFields.email}
                handleChange={handleOnChange}
                handleErrorChange={handleErrorChange}
                errorMessage={errors.email || errors.username}
                helpText={[formatMessage(messages['help.text.email'])]}
                floatingLabel={formatMessage(messages['registration.email.label'])}
              />

              <Form.Group className="mb-4">
                <Form.Control
                  name="user_role"
                  as="select"
                  value={formFields.user_role || 'student'}
                  onChange={handleOnChange}
                  floatingLabel={formatMessage(messages['registration.user.role.label'])}
                  isInvalid={!!errors.user_role}
                >
                  <option value="student">{formatMessage(messages['registration.user.role.option.student'])}</option>
                  <option value="mentor">{formatMessage(messages['registration.user.role.option.mentor'])}</option>
                </Form.Control>
                {errors.user_role && <Form.Text className="text-danger">{errors.user_role}</Form.Text>}
              </Form.Group>

              <Form.Group className="mb-4 d-flex gap-2">
                <Form.Control
                  name="phone_number"
                  type="text"
                  value={formFields.phone_number || ''}
                  onChange={handleOnChange}
                  floatingLabel={formatMessage(messages['registration.phone.number.label'])}
                  placeholder={formatMessage(messages['registration.phone.number.placeholder'])}
                  isInvalid={!!errors.phone_number}
                />
                {errors.phone_number && <Form.Text className="text-danger">{errors.phone_number}</Form.Text>}

                {formFields.phone_number?.length >= 10 && !otpState.otpVerified && (
                  <button
                    type="button"
                    className="btn btn-outline-primary h-100"
                    onClick={otpState.otpSent ? resendOtp : sendOtp}
                    disabled={otpState.sending || otpState.resending || (otpState.otpSent && otpState.resendIn > 0)}
                    style={{ height: '38px', marginTop: '1px' }}
                  >
                    {otpState.otpSent
                      ? otpState.resending
                        ? formatMessage(messages['registration.otp.resending'])
                        : otpState.resendIn > 0
                        ? `${formatMessage(messages['registration.otp.resend.button'])} (${otpState.resendIn}${formatMessage(messages['registration.otp.second'])})`
                        : formatMessage(messages['registration.otp.resend.button'])
                      : otpState.sending
                      ? formatMessage(messages['registration.otp.sending'])
                      : formatMessage(messages['registration.otp.send.button'])}
                  </button>
                )}
              </Form.Group>

              {otpState.otpSent && !otpState.otpVerified && (
                <Form.Group className="mb-4 d-flex gap-2">
                  <Form.Control
                    name="otp_code"
                    type="text"
                    value={otpState.otpCode}
                    onChange={(e) => setOtpState((prev) => ({ ...prev, otpCode: e.target.value }))}
                    floatingLabel={formatMessage(messages['registration.otp.enter.label'])}
                    placeholder={formatMessage(messages['registration.otp.placeholder'])}
                  />
                  <button
                    type="button"
                    className="btn btn-success"
                    onClick={verifyOtp}
                    disabled={!otpState.otpCode || otpState.verifying}
                  >
                    {otpState.verifying ? formatMessage(messages['registration.otp.verifying']) : formatMessage(messages['registration.otp.verify.button'])}
                  </button>
                </Form.Group>
              )}

              {otpState.otpVerified && (
                <div className="alert alert-success mb-4">{formatMessage(messages['registration.phone.verified.success'])}</div>
              )}

              {otpState.serverMessage && !otpState.otpVerified && (
                <div className="alert alert-danger mb-4">{otpState.serverMessage}</div>
              )}

              <PasswordField
                name="password"
                value={formFields.password}
                handleChange={handleOnChange}
                handleErrorChange={handleErrorChange}
                errorMessage={errors.password}
                floatingLabel={formatMessage(messages['registration.password.label'])}
              />

              <Form.Group className="mb-4">
                <Form.Control
                  name="confirm_password"
                  type="password"
                  value={formFields.confirm_password || ''}
                  onChange={handleOnChange}
                  floatingLabel={formatMessage(messages['registration.confirm.password.label'])}
                  placeholder={formatMessage(messages['registration.confirm.password.placeholder'])}
                  isInvalid={!!errors.confirm_password}
                />
                {errors.confirm_password && <Form.Text className="text-danger">{errors.confirm_password}</Form.Text>}
              </Form.Group>

              <TermsOfService
                value={formFields.terms_of_service}
                onChangeHandler={handleOnChange}
                errorMessage={errors.terms_of_service || ''}
              />

              <StatefulButton
                id="register-user"
                name="register-user"
                type="submit"
                variant="brand"
                className="register-button mt-4 mb-4"
                state={submitState}
                labels={{ default: buttonLabel, pending: '' }}
                // onClick={handleSubmit}
                // onMouseDown={(e) => e.preventDefault()}
              />

              {!registrationEmbedded && (
                <ThirdPartyAuth
                  currentProvider={currentProvider}
                  providers={providers}
                  secondaryProviders={secondaryProviders}
                  handleInstitutionLogin={handleInstitutionLogin}
                  thirdPartyAuthApiStatus={thirdPartyAuthApiStatus}
                />
              )}
            </Form>
          </div>
        )}
      </>
    );
  };

  if (tpaHint) {
    if (thirdPartyAuthApiStatus === PENDING_STATE) return <Skeleton height={36} />;
    const { provider, skipHintedLogin } = getTpaProvider(tpaHint, providers, secondaryProviders);
    if (skipHintedLogin) {
      window.location.href = getConfig().LMS_BASE_URL + provider.registerUrl;
      return null;
    }
    return provider ? <EnterpriseSSO provider={provider} /> : renderForm();
  }

  return renderForm();
};

CustomRegistrationPage.propTypes = {
  institutionLogin: PropTypes.bool,
  handleInstitutionLogin: PropTypes.func,
};

CustomRegistrationPage.defaultProps = {
  handleInstitutionLogin: null,
  institutionLogin: false,
};

export default CustomRegistrationPage;